import * as React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Printer } from "lucide-react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthProvider";
import { LoadingState, ErrorState } from "../components/states";
import { fmtDate } from "../lib/labels";
import type { Participant, ServiceAgreement } from "../types/database";

export default function AgreementDocument() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { currentOrg } = useAuth();
  const [a, setA] = React.useState<ServiceAgreement | null>(null);
  const [p, setP] = React.useState<Participant | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(true);

  const load = React.useCallback(async () => {
    if (!id) return;
    setLoading(true); setError(null);
    const { data, error } = await supabase.from("service_agreements").select("*").eq("id", id).maybeSingle();
    if (error || !data) { setError(error?.message ?? "Not found"); setLoading(false); return; }
    setA(data as ServiceAgreement);
    const { data: pp } = await supabase.from("participants").select("*").eq("id", (data as ServiceAgreement).participant_id).maybeSingle();
    setP(pp as Participant);
    setLoading(false);
  }, [id]);

  React.useEffect(() => { load(); }, [load]);

  if (loading) return <div className="p-10"><LoadingState /></div>;
  if (error || !a) return <div className="p-10"><ErrorState message={error ?? "Error"} onRetry={load} /></div>;

  return (
    <div className="min-h-screen bg-white">
      <style>{`@media print { .no-print { display:none !important; } }`}</style>
      <div className="no-print sticky top-0 flex items-center justify-between border-b border-line bg-surface px-6 py-3">
        <button onClick={() => navigate(`/participants/${a.participant_id}`)} className="flex items-center gap-1.5 text-sm text-ink-500 hover:text-ink">
          <ArrowLeft className="h-4 w-4" /> Back
        </button>
        <button onClick={() => window.print()} className="flex items-center gap-1.5 rounded-md bg-brand-700 px-3 py-1.5 text-sm font-medium text-white hover:bg-brand-600">
          <Printer className="h-4 w-4" /> Print / Save as PDF
        </button>
      </div>

      <div className="mx-auto max-w-3xl px-8 py-10 text-ink">
        <header className="mb-8 text-center">
          <p className="text-xs uppercase tracking-wide text-ink-500">{currentOrg?.name}</p>
          <h1 className="mt-1 text-2xl font-semibold">{a.title}</h1>
        </header>

        <Block label="Parties" value={a.parties} />
        <Block label="Participant" value={p ? `${p.first_name} ${p.last_name}${p.ndis_number ? ` · NDIS ${p.ndis_number}` : ""}` : "—"} />
        <Block label="Term" value={a.start_date ? `${fmtDate(a.start_date)} to ${fmtDate(a.end_date)}` : "—"} />
        <Block label="Supports provided" value={a.supports} />
        <Block label="Terms & conditions" value={a.terms} />
        {a.notes && <Block label="Notes" value={a.notes} />}

        <div className="mt-12 grid grid-cols-2 gap-10">
          <Sign label="Participant / nominee" name={p ? `${p.first_name} ${p.last_name}` : ""} date={a.signed_at} />
          <Sign label={currentOrg?.name ?? "Provider"} name={a.signer_name ?? ""} date={a.signed_at} />
        </div>

        <p className="mt-10 text-center text-xs text-ink-500">
          Status: {a.status}{a.signed_at ? ` · signed ${fmtDate(a.signed_at)}` : ""}. Generated by Coordinator OS.
        </p>
      </div>
    </div>
  );
}

function Block({ label, value }: { label: string; value?: string | null }) {
  return (
    <section className="mb-5">
      <h2 className="mb-1 text-sm font-semibold uppercase tracking-wide text-brand-700">{label}</h2>
      <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink">{value || "—"}</p>
    </section>
  );
}

function Sign({ label, name, date }: { label: string; name: string; date: string | null }) {
  return (
    <div>
      <div className="h-12 border-b border-ink" />
      <p className="mt-1 text-sm font-medium text-ink">{name || " "}</p>
      <p className="text-xs text-ink-500">{label}{date ? ` · ${fmtDate(date)}` : ""}</p>
    </div>
  );
}
